# render.yaml
services:
  - type: web
    name: bot-whatsapp
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: PORT
        value: "3000"
    persistentDirectories:
      - path: /mnt/data/auth_info
        description: "Directorio para guardar la sesi√≥n de WhatsApp"
